# Generated by Django 2.0.6 on 2020-05-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200514_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fanju',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=20)),
                ('is_delete', models.BooleanField(default=False)),
                ('mount', models.IntegerField()),
                ('pic', models.ImageField(default='img/1.jpg', upload_to='img')),
            ],
            options={
                'db_table': 'z_fanju',
            },
        ),
    ]
